### ISSUE TITLE
launcher.gcr.io container registry is deprecated

### ISSUE THREAD

**Issue by payaldtech** [GoogleCloudPlatform/nginx-docker#70]
As per [Google cloud documentation](https://cloud.google.com/marketplace/docs/container-images), the container registry launcher.gcr.io is deprecated.
Update `gcloud docker -- pull launcher.gcr.io/google/nginx1` to `gcloud docker -- pull marketplace.gcr.io/google/nginx1` in the README.MD file.

**Comment by EugeneKorolevich** [comment]
done in  4e127a10880152d8547e86b55c669f3388aab89a
